name: Docker (all)

on:
  schedule:
    - cron: '22 2 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tools:
    uses: ./.github/workflows/docker-tools.yml
  serve:
    uses: ./.github/workflows/docker-serve.yml
